[pytest]
asyncio_default_fixture_loop_scope = function
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short -p rhosocial.activerecord.testsuite.conftest
filterwarnings =
    ignore::DeprecationWarning
markers =
    requires_sqlserver: mark test as requiring SQL Server connection
    slow: mark test as slow running
