# src/rhosocial/activerecord/backend/impl/sqlserver/protocols/fulltext.py
from typing import List, Protocol, Tuple, Optional, runtime_checkable


@runtime_checkable
class SQLServerFullTextSearchSupport(Protocol):
    def supports_fulltext_catalog(self) -> bool: ...
    def format_create_fulltext_catalog_statement(
        self, catalog_name: str, as_default: bool = False
    ) -> str: ...
    def format_drop_fulltext_catalog_statement(self, catalog_name: str) -> str: ...
    def format_create_fulltext_index_statement(
        self,
        table: str,
        columns: List[str],
        key_index: str,
        catalog_name: str,
    ) -> str: ...
    def format_drop_fulltext_index_statement(self, table: str) -> str: ...
    def format_contains_predicate(self, column: str, search_string: str) -> Tuple[str, tuple]: ...
    def format_freetext_predicate(self, column: str, search_string: str) -> Tuple[str, tuple]: ...
    def format_containstable_function(
        self, table: str, column: str, search_string: str, top_n: Optional[int] = None
    ) -> Tuple[str, tuple]: ...
