# src/rhosocial/activerecord/backend/impl/sqlserver/protocols/temporal.py
from typing import Protocol, Tuple, runtime_checkable


@runtime_checkable
class SQLServerTemporalTableSupport(Protocol):
    def supports_system_versioning(self) -> bool: ...
    def format_create_temporal_table_statement(self, expr: object) -> Tuple[str, tuple]: ...
    def format_temporal_period_definition(self, start_column: str, end_column: str) -> Tuple[str, tuple]: ...