# src/rhosocial/activerecord/backend/impl/sqlserver/protocols/try_cast.py
from typing import Protocol, Tuple, Optional, runtime_checkable


@runtime_checkable
class SQLServerTryCastSupport(Protocol):
    def supports_try_cast(self) -> bool: ...
    def supports_try_convert(self) -> bool: ...
    def format_try_cast_expression(self, expr_sql: str, target_type: str) -> Tuple[str, tuple]: ...
    def format_try_convert_expression(
        self, expr_sql: str, target_type: str, style: Optional[int] = None
    ) -> Tuple[str, tuple]: ...