# src/rhosocial/activerecord/backend/impl/sqlserver/examples/insert/output.py
"""INSERT with OUTPUT clause examples.

SQL Server uses the OUTPUT clause (similar to RETURNING in PostgreSQL)
to return data from INSERT, UPDATE, and DELETE operations.
"""

import yaml
from pathlib import Path

from rhosocial.activerecord.backend.impl.sqlserver import (
    SQLServerBackend,
    SQLServerConnectionConfig,
)


def get_backend():
    """Get a configured backend instance."""
    config_path = Path(__file__).parent.parent.parent.parent.parent.parent / "tests" / "config" / "sqlserver_scenarios.yaml"
    
    config = {}
    if config_path.exists():
        with open(config_path, 'r') as f:
            config_data = yaml.safe_load(f)
            config = config_data.get('scenarios', {}).get('sqlserver_2022', {})
    
    backend = SQLServerBackend(
        connection_config=SQLServerConnectionConfig(
            host=config.get('host', 'localhost'),
            port=config.get('port', 1433),
            database=config.get('database', 'test_db'),
            username=config.get('username', 'sa'),
            password=config.get('password', ''),
            driver=config.get('driver', 'ODBC Driver 17 for SQL Server'),
            encrypt=config.get('encrypt', False),
            trust_server_certificate=config.get('trust_server_certificate', True),
            autocommit=False,
        )
    )
    
    return backend


def setup_table(backend):
    """Create test table for examples."""
    backend.execute("""
        IF OBJECT_ID('output_test', 'U') IS NOT NULL
            DROP TABLE output_test
    """)
    
    backend.execute("""
        CREATE TABLE output_test (
            id INT IDENTITY(1,1) PRIMARY KEY,
            name NVARCHAR(100) NOT NULL,
            created_at DATETIME2 DEFAULT SYSDATETIME(),
            status NVARCHAR(20) DEFAULT 'active'
        )
    """)


def example_insert_output():
    """Example: INSERT with OUTPUT clause.
    
    The OUTPUT clause returns the inserted rows, including
    identity values generated by IDENTITY columns.
    
    SQL Syntax:
        INSERT INTO table (columns)
        OUTPUT inserted.column1, inserted.column2
        VALUES (values)
    """
    backend = get_backend()
    backend.connect()
    
    try:
        backend.transaction_manager.begin()
        setup_table(backend)
        
        result = backend.execute("""
            INSERT INTO output_test (name)
            OUTPUT inserted.id, inserted.name, inserted.created_at
            VALUES ('Test User 1')
        """)
        
        if result.data:
            row = result.data[0]
            print(f"Inserted row:")
            print(f"  ID: {row['id']}")
            print(f"  Name: {row['name']}")
            print(f"  Created: {row['created_at']}")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_insert_output_into():
    """Example: INSERT with OUTPUT INTO a table variable.
    
    OUTPUT INTO can insert the output into a table variable
    or temporary table for further processing.
    """
    backend = get_backend()
    backend.connect()
    
    try:
        backend.transaction_manager.begin()
        
        backend.execute("""
            DECLARE @inserted TABLE (id INT, name NVARCHAR(100), created_at DATETIME2);
            
            INSERT INTO output_test (name)
            OUTPUT inserted.id, inserted.name, inserted.created_at
            INTO @inserted
            VALUES ('User A'), ('User B'), ('User C');
            
            SELECT * FROM @inserted;
        """)
        
        backend.transaction_manager.commit()
        print("Inserted 3 rows with OUTPUT INTO")
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_update_output():
    """Example: UPDATE with OUTPUT clause.
    
    OUTPUT can return both old (deleted) and new (inserted) values
    for UPDATE operations.
    """
    backend = get_backend()
    backend.connect()
    
    try:
        backend.transaction_manager.begin()
        
        result = backend.execute("""
            UPDATE output_test
            SET status = 'inactive'
            OUTPUT 
                deleted.id,
                deleted.name AS old_name,
                inserted.name AS new_name,
                deleted.status AS old_status,
                inserted.status AS new_status
            WHERE name LIKE 'Test%'
        """)
        
        print(f"Updated {result.affected_rows} rows")
        for row in result.data:
            print(f"  Row {row['id']}: status changed from '{row['old_status']}' to '{row['new_status']}'")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_delete_output():
    """Example: DELETE with OUTPUT clause.
    
    OUTPUT returns the deleted rows for DELETE operations.
    """
    backend = get_backend()
    backend.connect()
    
    try:
        backend.transaction_manager.begin()
        
        result = backend.execute("""
            DELETE FROM output_test
            OUTPUT deleted.id, deleted.name, deleted.status
            WHERE status = 'inactive'
        """)
        
        print(f"Deleted {result.affected_rows} rows:")
        for row in result.data:
            print(f"  Deleted: {row['name']} (id={row['id']})")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_merge_output():
    """Example: MERGE statement with OUTPUT clause.
    
    MERGE is SQL Server's native upsert mechanism, supporting
    INSERT, UPDATE, and DELETE in a single statement.
    """
    backend = get_backend()
    backend.connect()
    
    try:
        backend.transaction_manager.begin()
        
        backend.execute("""
            CREATE TABLE #source (name NVARCHAR(100), status NVARCHAR(20));
            INSERT INTO #source VALUES ('User A', 'active'), ('User D', 'new');
        """)
        
        result = backend.execute("""
            MERGE INTO output_test AS target
            USING #source AS source
            ON target.name = source.name
            WHEN MATCHED THEN
                UPDATE SET status = source.status
            WHEN NOT MATCHED THEN
                INSERT (name, status)
                VALUES (source.name, source.status)
            OUTPUT 
                $action AS action,
                inserted.id,
                inserted.name,
                inserted.status;
        """)
        
        print("MERGE results:")
        for row in result.data:
            print(f"  {row['action']}: {row['name']} (id={row['id']})")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def cleanup():
    """Clean up test tables."""
    backend = get_backend()
    backend.connect()
    backend.execute("DROP TABLE IF EXISTS output_test")
    backend.disconnect()


def main():
    """Run all OUTPUT clause examples."""
    print("=" * 60)
    print("SQL Server OUTPUT Clause Examples")
    print("=" * 60)
    
    examples = [
        ("INSERT with OUTPUT", example_insert_output),
        ("UPDATE with OUTPUT", example_update_output),
        ("DELETE with OUTPUT", example_delete_output),
        ("MERGE with OUTPUT", example_merge_output),
    ]
    
    for name, func in examples:
        print(f"\n{name}:")
        try:
            func()
            print("   ✓ Success")
        except Exception as e:
            print(f"   ✗ Error: {e}")
    
    print("\n" + "=" * 60)
    cleanup()
    print("OUTPUT clause examples completed")


if __name__ == "__main__":
    main()
