"""INSERT with OUTPUT clause examples.

SQL Server uses the OUTPUT clause (similar to RETURNING in PostgreSQL)
to return data from INSERT, UPDATE, and DELETE operations.

Connection configuration is loaded from environment variables with defaults.
"""

import os

from rhosocial.activerecord.backend.impl.sqlserver import (
    SQLServerBackend,
    SQLServerConnectionConfig,
)


def get_backend():
    """Get a configured backend instance from environment variables."""
    config = SQLServerConnectionConfig(
        host=os.environ.get('SQLSERVER_HOST', 'localhost'),
        port=int(os.environ.get('SQLSERVER_PORT', '11434')),
        database=os.environ.get('SQLSERVER_DATABASE', 'test_db'),
        username=os.environ.get('SQLSERVER_USERNAME', 'sa'),
        password=os.environ.get('SQLSERVER_PASSWORD', 'Password123!'),
        driver=os.environ.get('SQLSERVER_DRIVER', 'SQL Server'),
        encrypt=os.environ.get('SQLSERVER_ENCRYPT', 'false').lower() == 'true',
        trust_server_certificate=os.environ.get('SQLSERVER_TRUST_SERVER_CERTIFICATE', 'true').lower() == 'true',
        autocommit=False,
    )
    
    backend = SQLServerBackend(connection_config=config)
    backend.connect()
    return backend


def setup_table(backend):
    """Create test table for examples."""
    backend.execute("""
        IF OBJECT_ID('output_test', 'U') IS NOT NULL
            DROP TABLE output_test
    """)
    
    backend.execute("""
        CREATE TABLE output_test (
            id INT IDENTITY(1,1) PRIMARY KEY,
            name NVARCHAR(100) NOT NULL,
            created_at DATETIME2 DEFAULT SYSDATETIME(),
            status NVARCHAR(20) DEFAULT 'active'
        )
    """)


def example_insert_output():
    """Example: INSERT with OUTPUT clause.
    
    The OUTPUT clause returns the inserted rows, including
    identity values generated by IDENTITY columns.
    
    SQL Syntax:
        INSERT INTO table (columns)
        OUTPUT inserted.column1, inserted.column2
        VALUES (values)
    """
    print("\n--- INSERT with OUTPUT ---")
    backend = get_backend()
    
    try:
        backend.transaction_manager.begin()
        setup_table(backend)
        
        result = backend.execute("""
            INSERT INTO output_test (name)
            OUTPUT inserted.id, inserted.name, inserted.created_at
            VALUES ('Test User 1')
        """)
        
        if result.data:
            row = result.data[0]
            print(f"Inserted row:")
            print(f"  ID: {row['id']}")
            print(f"  Name: {row['name']}")
            print(f"  Created: {row['created_at']}")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_multi_insert_output():
    """Example: Multi-row INSERT with OUTPUT."""
    print("\n--- Multi-row INSERT with OUTPUT ---")
    backend = get_backend()
    
    try:
        backend.transaction_manager.begin()
        
        result = backend.execute("""
            INSERT INTO output_test (name, status)
            OUTPUT inserted.id, inserted.name, inserted.status
            VALUES 
                ('User A', 'active'),
                ('User B', 'inactive'),
                ('User C', 'active')
        """)
        
        print(f"Inserted {len(result.data)} rows:")
        for row in result.data:
            print(f"  ID: {row['id']}, Name: {row['name']}, Status: {row['status']}")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_update_output():
    """Example: UPDATE with OUTPUT clause.
    
    OUTPUT can return both old (deleted) and new (inserted) values
    for UPDATE operations.
    """
    print("\n--- UPDATE with OUTPUT ---")
    backend = get_backend()
    
    try:
        backend.transaction_manager.begin()
        
        result = backend.execute("""
            UPDATE output_test
            SET status = 'inactive'
            OUTPUT 
                deleted.id,
                deleted.name AS old_name,
                inserted.name AS new_name,
                deleted.status AS old_status,
                inserted.status AS new_status
            WHERE name LIKE 'Test%'
        """)
        
        print(f"Updated {result.affected_rows} rows")
        for row in result.data:
            print(f"  Row {row['id']}: status changed from '{row['old_status']}' to '{row['new_status']}'")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_delete_output():
    """Example: DELETE with OUTPUT clause.
    
    OUTPUT returns the deleted rows for DELETE operations.
    """
    print("\n--- DELETE with OUTPUT ---")
    backend = get_backend()
    
    try:
        backend.transaction_manager.begin()
        
        result = backend.execute("""
            DELETE FROM output_test
            OUTPUT deleted.id, deleted.name, deleted.status
            WHERE status = 'inactive'
        """)
        
        print(f"Deleted {result.affected_rows} rows:")
        for row in result.data:
            print(f"  Deleted: {row['name']} (id={row['id']})")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def example_merge_output():
    """Example: MERGE statement with OUTPUT clause.
    
    MERGE is SQL Server's native upsert mechanism, supporting
    INSERT, UPDATE, and DELETE in a single statement.
    """
    print("\n--- MERGE with OUTPUT ---")
    backend = get_backend()
    
    try:
        backend.transaction_manager.begin()
        
        # Create source data
        backend.execute("""
            CREATE TABLE #source (name NVARCHAR(100), status NVARCHAR(20));
            INSERT INTO #source VALUES ('User A', 'active'), ('User D', 'new');
        """)
        
        result = backend.execute("""
            MERGE INTO output_test AS target
            USING #source AS source
            ON target.name = source.name
            WHEN MATCHED THEN
                UPDATE SET status = source.status
            WHEN NOT MATCHED THEN
                INSERT (name, status)
                VALUES (source.name, source.status)
            OUTPUT 
                $action AS action,
                inserted.id,
                inserted.name,
                inserted.status;
        """)
        
        print("MERGE results:")
        for row in result.data:
            print(f"  {row['action']}: {row['name']} (id={row['id']})")
        
        backend.transaction_manager.commit()
        
    except Exception as e:
        backend.transaction_manager.rollback()
        print(f"Error: {e}")
    
    finally:
        backend.disconnect()


def cleanup():
    """Clean up test tables."""
    backend = get_backend()
    backend.execute("DROP TABLE IF EXISTS output_test")
    backend.disconnect()


def main():
    """Run all OUTPUT clause examples."""
    print("=" * 60)
    print("SQL Server OUTPUT Clause Examples")
    print("=" * 60)
    
    examples = [
        ("INSERT with OUTPUT", example_insert_output),
        ("Multi-row INSERT", example_multi_insert_output),
        ("UPDATE with OUTPUT", example_update_output),
        ("DELETE with OUTPUT", example_delete_output),
        ("MERGE with OUTPUT", example_merge_output),
    ]
    
    for name, func in examples:
        try:
            func()
            print(f"   ✓ {name} completed")
        except Exception as e:
            print(f"   ✗ {name} failed: {e}")
    
    print("\n" + "=" * 60)
    cleanup()
    print("OUTPUT clause examples completed")


if __name__ == "__main__":
    main()
